; SMT 2
; Generated for Z3
(set-info :source "Generated by CBMC 5.10 (cbmc-5.10-3-ga218aeb-dirty)")
(set-option :produce-models true)

; find_symbols
(declare-fun |goto_symex::&92;guard#1| () Bool)
; convert
(define-fun |B0| () Bool |goto_symex::&92;guard#1|)

; convert
(define-fun |B1| () Bool |goto_symex::&92;guard#1|)

; convert
(define-fun |B2| () Bool (not |goto_symex::&92;guard#1|))

; find_symbols
(declare-fun |goto_symex::&92;guard#2| () Bool)
; convert
(define-fun |B3| () Bool (and (not |goto_symex::&92;guard#1|) |goto_symex::&92;guard#2|))

; convert
(define-fun |B4| () Bool (and (not |goto_symex::&92;guard#1|) |goto_symex::&92;guard#2|))

; convert
(define-fun |B5| () Bool (and (not |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|)))

; convert
(define-fun |B6| () Bool (and (not |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#2| () (Array (_ BitVec 64) Bool))
; find_symbols
(declare-fun |pthread_join::thread!0@1#1| () (_ BitVec 64))
; convert
(define-fun |B7| () Bool (and (not |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#2|) (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)))

; convert
(define-fun |B8| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B9| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B10| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B11| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B12| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B13| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B14| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B15| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; convert
(define-fun |B16| () Bool (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; find_symbols
(declare-fun |goto_symex::&92;guard#3| () Bool)
; convert
(define-fun |B17| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) |goto_symex::&92;guard#3|))

; convert
(define-fun |B18| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) |goto_symex::&92;guard#3|))

; convert
(define-fun |B19| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#4| () Bool)
; convert
(define-fun |B20| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|) |goto_symex::&92;guard#4|))

; convert
(define-fun |B21| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|) |goto_symex::&92;guard#4|))

; convert
(define-fun |B22| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#4|)))

; convert
(define-fun |B23| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#4|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#3| () (Array (_ BitVec 64) Bool))
; find_symbols
(declare-fun |pthread_join::thread!0@2#1| () (_ BitVec 64))
; convert
(define-fun |B24| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (not |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#4|) (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)))

; convert
(define-fun |B25| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B26| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B27| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B28| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B29| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B30| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B31| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B32| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B33| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B34| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B35| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B36| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B37| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; convert
(define-fun |B38| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#5| () Bool)
; convert
(define-fun |B39| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) |goto_symex::&92;guard#5|))

; convert
(define-fun |B40| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B41| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B42| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B43| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B44| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B45| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; convert
(define-fun |B46| () Bool (and (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|) (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|) (not |goto_symex::&92;guard#5|)))

; find_symbols
(declare-fun |goto_symex::&92;guard#6| () Bool)
; convert
(define-fun |B47| () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun |B48| () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun |B49| () Bool |goto_symex::&92;guard#6|)

; convert
(define-fun |B50| () Bool |goto_symex::&92;guard#6|)

; find_symbols
(declare-fun |goto_symex::&92;guard#7| () Bool)
; convert
(define-fun |B51| () Bool |goto_symex::&92;guard#7|)

; convert
(define-fun |B52| () Bool |goto_symex::&92;guard#7|)

; convert
(define-fun |B53| () Bool |goto_symex::&92;guard#7|)

; convert
(define-fun |B54| () Bool |goto_symex::&92;guard#7|)

; set_to true (equal)
(define-fun |__CPROVER_dead_object#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_deallocated#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_malloc_is_new_array#1| () Bool false)

; set_to true (equal)
(define-fun |__CPROVER_malloc_object#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_malloc_size#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_memory_leak#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_next_thread_id#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_pipe_count#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |__CPROVER_rounding_mode!0#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |__CPROVER_thread_id!0#1| () (_ BitVec 64) (_ bv0 64))

; the following is a substitute for lambda i. x
(declare-fun array_of.0 () (Array (_ BitVec 64) Bool))
; set_to true (equal)
(define-fun |__CPROVER_threads_exited#1| () (Array (_ BitVec 64) Bool) array_of.0)

; set_to true (equal)
(define-fun |a#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |b#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |main::1::a_in!0@1#2| () (_ BitVec 32) (_ bv8 32))

; set_to true (equal)
(define-fun |main::1::b_in!0@1#2| () (_ BitVec 32) (_ bv6 32))

; set_to true (equal)
(define-fun |start::a_in!0@1#1| () (_ BitVec 32) (_ bv8 32))

; set_to true (equal)
(define-fun |start::b_in!0@1#1| () (_ BitVec 32) (_ bv6 32))

; set_to true (equal)
(define-fun |a#2| () (_ BitVec 32) (_ bv8 32))

; set_to true (equal)
(define-fun |b#2| () (_ BitVec 32) (_ bv6 32))

; find_symbols
(declare-fun |start::1::t1!0@1| () (_ BitVec 64))
; set_to true (equal)
(define-fun |pthread_create::thread!0@1#1| () (_ BitVec 64) (concat (_ bv2 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::attr!0@1#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create::start_routine!0@1#1| () (_ BitVec 64) (concat (_ bv3 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::arg!0@1#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_next_thread_id#2| () (_ BitVec 64) (_ bv1 64))

; set_to true (equal)
(define-fun |pthread_create::1::this_thread_id!0@1#2| () (_ BitVec 64) (_ bv1 64))

; set_to true (equal)
(define-fun |start::1::t1!0@1#2| () (_ BitVec 64) (_ bv1 64))

; set_to true (equal)
(define-fun |pthread_create::thread!1@0#1| () (_ BitVec 64) (concat (_ bv2 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::attr!1@0#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create::start_routine!1@0#1| () (_ BitVec 64) (concat (_ bv3 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::arg!1@0#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_join#return_value!1#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |dec_b#return_value!1#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_thread_id!1#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |main#return_value!1#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |__CPROVER_rounding_mode!1#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |dec_a#return_value!1#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create#return_value!1#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |start#return_value!1#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |pthread_create#return_value!0#1| () (_ BitVec 32) (_ bv0 32))

; find_symbols
(declare-fun |start::1::t2!0@1| () (_ BitVec 64))
; set_to true (equal)
(define-fun |pthread_create::thread!0@2#1| () (_ BitVec 64) (concat (_ bv4 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::attr!0@2#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create::start_routine!0@2#1| () (_ BitVec 64) (concat (_ bv5 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::arg!0@2#1| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#3| () (_ BitVec 64))
; set_to true (equal)
(define-fun |__CPROVER_next_thread_id#4| () (_ BitVec 64) |__CPROVER_next_thread_id#3|)

; set_to true (equal)
(define-fun |__CPROVER_next_thread_id#5| () (_ BitVec 64) (bvadd (_ bv1 64) |__CPROVER_next_thread_id#4|))

; set_to true (equal)
(define-fun |pthread_create::1::this_thread_id!0@2#2| () (_ BitVec 64) |__CPROVER_next_thread_id#5|)

; set_to true (equal)
(define-fun |start::1::t2!0@1#2| () (_ BitVec 64) |pthread_create::1::this_thread_id!0@2#2|)

; set_to true (equal)
(define-fun |pthread_create::thread!2@0#1| () (_ BitVec 64) (concat (_ bv4 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::attr!2@0#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create::start_routine!2@0#1| () (_ BitVec 64) (concat (_ bv5 8) (_ bv0 56)))

; set_to true (equal)
(define-fun |pthread_create::arg!2@0#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_join#return_value!2#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |dec_b#return_value!2#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |__CPROVER_thread_id!2#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |main#return_value!2#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |__CPROVER_rounding_mode!2#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |dec_a#return_value!2#1| () (_ BitVec 64) (_ bv0 64))

; set_to true (equal)
(define-fun |pthread_create#return_value!2#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |start#return_value!2#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |pthread_create#return_value!0#2| () (_ BitVec 32) (_ bv0 32))

; find_symbols
(declare-fun |start::1::t1!0@1#4| () (_ BitVec 64))
; set_to true
(assert (= |pthread_join::thread!0@1#1| |start::1::t1!0@1#4|))

; set_to true (equal)
(define-fun |pthread_join::value_ptr!0@1#1| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#6| () (_ BitVec 64))
; set_to true
(assert (= |goto_symex::&92;guard#1| (not (bvuge |__CPROVER_next_thread_id#6| |pthread_join::thread!0@1#1|))))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#1| () (_ BitVec 32) (_ bv3 32))

; find_symbols
(declare-fun |pthread_join#return_value!0#0| () (_ BitVec 32))
; set_to true (equal)
(define-fun |pthread_join#return_value!0#2| () (_ BitVec 32) |pthread_join#return_value!0#0|)

; set_to true
(assert (= |goto_symex::&92;guard#2| (= |pthread_join::thread!0@1#1| (_ bv0 64))))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#3| () (_ BitVec 32) (_ bv35 32))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#4| () (_ BitVec 32) |pthread_join#return_value!0#2|)

; set_to true (equal)
(define-fun |pthread_join#return_value!0#5| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#6| () (_ BitVec 32) (ite |goto_symex::&92;guard#2| (_ bv35 32) (_ bv0 32)))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#7| () (_ BitVec 32) (ite |goto_symex::&92;guard#1| (_ bv3 32) |pthread_join#return_value!0#6|))

; find_symbols
(declare-fun |start::1::t2!0@1#4| () (_ BitVec 64))
; set_to true
(assert (= |pthread_join::thread!0@2#1| |start::1::t2!0@1#4|))

; set_to true (equal)
(define-fun |pthread_join::value_ptr!0@2#1| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#7| () (_ BitVec 64))
; set_to true
(assert (= |goto_symex::&92;guard#3| (not (bvuge |__CPROVER_next_thread_id#7| |pthread_join::thread!0@2#1|))))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#8| () (_ BitVec 32) (_ bv3 32))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#9| () (_ BitVec 32) |pthread_join#return_value!0#7|)

; set_to true
(assert (= |goto_symex::&92;guard#4| (= |pthread_join::thread!0@2#1| (_ bv0 64))))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#10| () (_ BitVec 32) (_ bv35 32))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#11| () (_ BitVec 32) |pthread_join#return_value!0#9|)

; set_to true (equal)
(define-fun |pthread_join#return_value!0#12| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#13| () (_ BitVec 32) (ite |goto_symex::&92;guard#4| (_ bv35 32) (_ bv0 32)))

; set_to true (equal)
(define-fun |pthread_join#return_value!0#14| () (_ BitVec 32) (ite |goto_symex::&92;guard#3| (_ bv3 32) |pthread_join#return_value!0#13|))

; find_symbols
(declare-fun |a#3| () (_ BitVec 32))
; set_to true (equal)
(define-fun |start#return_value!0#1| () (_ BitVec 32) |a#3|)

; set_to true (equal)
(define-fun |main::$tmp::return_value_start!0@1#2| () (_ BitVec 32) |start#return_value!0#1|)

; set_to true (equal)
(define-fun |check_gcd::a_in!0@1#1| () (_ BitVec 32) (_ bv8 32))

; set_to true (equal)
(define-fun |check_gcd::b_in!0@1#1| () (_ BitVec 32) (_ bv6 32))

; set_to true (equal)
(define-fun |check_gcd::gcd!0@1#1| () (_ BitVec 32) |main::$tmp::return_value_start!0@1#2|)

; set_to true (equal)
(define-fun |__VERIFIER_assert::cond!0@1#1| () (_ BitVec 32) (ite (and (not (= |check_gcd::gcd!0@1#1| (_ bv6 32))) (not (= |check_gcd::gcd!0@1#1| (_ bv8 32)))) (_ bv1 32) (_ bv0 32)))

; set_to true
(assert (= |goto_symex::&92;guard#5| (= |__VERIFIER_assert::cond!0@1#1| (_ bv0 32))))

; set_to true (equal)
(define-fun |main#return_value!0#1| () (_ BitVec 32) (_ bv0 32))

; set_to true (equal)
(define-fun |return'!0#1| () (_ BitVec 32) (_ bv0 32))

; find_symbols
(declare-fun |pthread_create::1::this_thread_id!1@0#0| () (_ BitVec 64))
; set_to true (equal)
(define-fun |__CPROVER_thread_id!1#2| () (_ BitVec 64) |pthread_create::1::this_thread_id!1@0#0|)

; set_to true (equal)
(define-fun |dec_a::arg!1@1#1| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |b#3| () (_ BitVec 32))
; find_symbols
(declare-fun |a#4| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#6| (not (bvuge |b#3| |a#4|))))

; find_symbols
(declare-fun |a#5| () (_ BitVec 32))
; find_symbols
(declare-fun |b#4| () (_ BitVec 32))
; set_to true (equal)
(define-fun |a#6| () (_ BitVec 32) (bvadd |a#5| (bvneg |b#4|)))

; set_to true (equal)
(define-fun |dec_a#return_value!1#2| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |__CPROVER_threads_exited#4| () (Array (_ BitVec 64) Bool))
; set_to true (equal)
(define-fun |__CPROVER_threads_exited#5| () (Array (_ BitVec 64) Bool) (store |__CPROVER_threads_exited#4| |pthread_create::1::this_thread_id!1@0#0| true))

; find_symbols
(declare-fun |pthread_create::1::this_thread_id!2@0#0| () (_ BitVec 64))
; set_to true (equal)
(define-fun |__CPROVER_thread_id!2#2| () (_ BitVec 64) |pthread_create::1::this_thread_id!2@0#0|)

; set_to true (equal)
(define-fun |dec_b::arg!2@1#1| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |a#7| () (_ BitVec 32))
; find_symbols
(declare-fun |b#5| () (_ BitVec 32))
; set_to true
(assert (= |goto_symex::&92;guard#7| (not (bvuge |a#7| |b#5|))))

; find_symbols
(declare-fun |b#6| () (_ BitVec 32))
; find_symbols
(declare-fun |a#8| () (_ BitVec 32))
; set_to true (equal)
(define-fun |b#7| () (_ BitVec 32) (bvadd |b#6| (bvneg |a#8|)))

; set_to true (equal)
(define-fun |dec_b#return_value!2#2| () (_ BitVec 64) (_ bv0 64))

; find_symbols
(declare-fun |__CPROVER_threads_exited#6| () (Array (_ BitVec 64) Bool))
; set_to true (equal)
(define-fun |__CPROVER_threads_exited#7| () (Array (_ BitVec 64) Bool) (store |__CPROVER_threads_exited#6| |pthread_create::1::this_thread_id!2@0#0| true))

; find_symbols
(declare-fun |main::1::a_in!0@1#1| () (_ BitVec 32))
; convert
(define-fun |B55| () Bool (= |main::1::a_in!0@1#1| |main::1::a_in!0@1#1|))

; find_symbols
(declare-fun |main::1::b_in!0@1#1| () (_ BitVec 32))
; convert
(define-fun |B56| () Bool (= |main::1::b_in!0@1#1| |main::1::b_in!0@1#1|))

; find_symbols
(declare-fun |main::$tmp::return_value_start!0@1#1| () (_ BitVec 32))
; convert
(define-fun |B57| () Bool (= |main::$tmp::return_value_start!0@1#1| |main::$tmp::return_value_start!0@1#1|))

; find_symbols
(declare-fun |start::1::t1!0@1#1| () (_ BitVec 64))
; convert
(define-fun |B58| () Bool (= |start::1::t1!0@1#1| |start::1::t1!0@1#1|))

; find_symbols
(declare-fun |start::1::t2!0@1#1| () (_ BitVec 64))
; convert
(define-fun |B59| () Bool (= |start::1::t2!0@1#1| |start::1::t2!0@1#1|))

; find_symbols
(declare-fun |pthread_create::1::this_thread_id!0@1#1| () (_ BitVec 64))
; convert
(define-fun |B60| () Bool (= |pthread_create::1::this_thread_id!0@1#1| |pthread_create::1::this_thread_id!0@1#1|))

; find_symbols
(declare-fun |pthread_create::1::this_thread_id!0@2#1| () (_ BitVec 64))
; convert
(define-fun |B61| () Bool (= |pthread_create::1::this_thread_id!0@2#1| |pthread_create::1::this_thread_id!0@2#1|))

; set_to true
(assert (or (and (not |goto_symex::&92;guard#1|) (or (and (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|) (not |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#2|)) |goto_symex::&92;guard#1|))

; set_to true
(assert (or (and (not |goto_symex::&92;guard#3|) (or (and (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|) (not |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#4|)) |goto_symex::&92;guard#3|))

; set_to true
(assert |goto_symex::&92;guard#5|)

; convert
(define-fun |B62| () Bool (bvuge |__CPROVER_next_thread_id#6| |pthread_join::thread!0@1#1|))

; convert
(define-fun |B63| () Bool (not (= |pthread_join::thread!0@1#1| (_ bv0 64))))

; convert
(define-fun |B64| () Bool (bvuge |__CPROVER_next_thread_id#7| |pthread_join::thread!0@2#1|))

; convert
(define-fun |B65| () Bool (not (= |pthread_join::thread!0@2#1| (_ bv0 64))))

; convert
(define-fun |B66| () Bool (not (= |__VERIFIER_assert::cond!0@1#1| (_ bv0 32))))

; convert
(define-fun |B67| () Bool (bvuge |b#3| |a#4|))

; convert
(define-fun |B68| () Bool (bvuge |a#7| |b#5|))

; find_symbols
(declare-fun |memory_model::choice_rf0| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#2| |__CPROVER_threads_exited#1|) (not |memory_model::choice_rf0|)))

; find_symbols
(declare-fun |memory_model::choice_rf1| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#2| |__CPROVER_threads_exited#5|) (not |memory_model::choice_rf1|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#5$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |__CPROVER_threads_exited#2$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#2$rclk$8|)) (not |memory_model::choice_rf1|)))

; find_symbols
(declare-fun |memory_model::choice_rf2| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#2| |__CPROVER_threads_exited#7|) (not |memory_model::choice_rf2|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#7$wclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#2$rclk$8|)) (not |memory_model::choice_rf2|)))

; set_to true
(assert (or |memory_model::choice_rf0| |memory_model::choice_rf1| |memory_model::choice_rf2| |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; find_symbols
(declare-fun |memory_model::choice_rf3| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#3| |__CPROVER_threads_exited#1|) (not |memory_model::choice_rf3|)))

; find_symbols
(declare-fun |memory_model::choice_rf4| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#3| |__CPROVER_threads_exited#5|) (not |memory_model::choice_rf4|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#3$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#3$rclk$8|)) (not |memory_model::choice_rf4|)))

; find_symbols
(declare-fun |memory_model::choice_rf5| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#3| |__CPROVER_threads_exited#7|) (not |memory_model::choice_rf5|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#3$rclk$8|)) (not |memory_model::choice_rf5|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) |memory_model::choice_rf3| |memory_model::choice_rf4| |memory_model::choice_rf5| |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; find_symbols
(declare-fun |memory_model::choice_rf6| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#4| |__CPROVER_threads_exited#1|) (not |memory_model::choice_rf6|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#1$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |__CPROVER_threads_exited#4$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#4$rclk$8|)) (not |memory_model::choice_rf6|)))

; find_symbols
(declare-fun |memory_model::choice_rf7| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#4| |__CPROVER_threads_exited#7|) (not |memory_model::choice_rf7|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#4$rclk$8|)) (not |memory_model::choice_rf7|)))

; set_to true
(assert (or |memory_model::choice_rf6| |memory_model::choice_rf7|))

; find_symbols
(declare-fun |memory_model::choice_rf8| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#6| |__CPROVER_threads_exited#1|) (not |memory_model::choice_rf8|)))

; find_symbols
(declare-fun |__CPROVER_threads_exited#6$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#6$rclk$8|)) (not |memory_model::choice_rf8|)))

; find_symbols
(declare-fun |memory_model::choice_rf9| () Bool)
; set_to true
(assert (or (= |__CPROVER_threads_exited#6| |__CPROVER_threads_exited#5|) (not |memory_model::choice_rf9|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#6$rclk$8|)) (not |memory_model::choice_rf9|)))

; set_to true
(assert (or |memory_model::choice_rf8| |memory_model::choice_rf9|))

; find_symbols
(declare-fun |memory_model::choice_rf10| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#3| |__CPROVER_next_thread_id#1|) (not |memory_model::choice_rf10|)))

; find_symbols
(declare-fun |memory_model::choice_rf11| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#3| |__CPROVER_next_thread_id#2|) (not |memory_model::choice_rf11|)))

; set_to true
(assert (or |memory_model::choice_rf10| |memory_model::choice_rf11|))

; find_symbols
(declare-fun |memory_model::choice_rf12| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#6| |__CPROVER_next_thread_id#1|) (not |memory_model::choice_rf12|)))

; find_symbols
(declare-fun |memory_model::choice_rf13| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#6| |__CPROVER_next_thread_id#2|) (not |memory_model::choice_rf13|)))

; find_symbols
(declare-fun |memory_model::choice_rf14| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#6| |__CPROVER_next_thread_id#5|) (not |memory_model::choice_rf14|)))

; set_to true
(assert (or |memory_model::choice_rf12| |memory_model::choice_rf13| |memory_model::choice_rf14|))

; find_symbols
(declare-fun |memory_model::choice_rf15| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#7| |__CPROVER_next_thread_id#1|) (not |memory_model::choice_rf15|)))

; find_symbols
(declare-fun |memory_model::choice_rf16| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#7| |__CPROVER_next_thread_id#2|) (not |memory_model::choice_rf16|)))

; find_symbols
(declare-fun |memory_model::choice_rf17| () Bool)
; set_to true
(assert (or (= |__CPROVER_next_thread_id#7| |__CPROVER_next_thread_id#5|) (not |memory_model::choice_rf17|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) |memory_model::choice_rf15| |memory_model::choice_rf16| |memory_model::choice_rf17|))

; find_symbols
(declare-fun |memory_model::choice_rf18| () Bool)
; set_to true
(assert (or (= |a#3| |a#1|) (not |memory_model::choice_rf18|)))

; find_symbols
(declare-fun |memory_model::choice_rf19| () Bool)
; set_to true
(assert (or (= |a#3| |a#2|) (not |memory_model::choice_rf19|)))

; find_symbols
(declare-fun |memory_model::choice_rf20| () Bool)
; set_to true
(assert (or (and (= |a#3| |a#6|) |goto_symex::&92;guard#6|) (not |memory_model::choice_rf20|)))

; find_symbols
(declare-fun |a#6$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |a#3$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#6$wclk$8| |a#3$rclk$8|)) (not |memory_model::choice_rf20|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) |memory_model::choice_rf18| |memory_model::choice_rf19| |memory_model::choice_rf20|))

; find_symbols
(declare-fun |memory_model::choice_rf21| () Bool)
; set_to true
(assert (or (= |a#4| |a#1|) (not |memory_model::choice_rf21|)))

; find_symbols
(declare-fun |a#1$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |a#4$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#1$wclk$8| |a#4$rclk$8|)) (not |memory_model::choice_rf21|)))

; find_symbols
(declare-fun |memory_model::choice_rf22| () Bool)
; set_to true
(assert (or (= |a#4| |a#2|) (not |memory_model::choice_rf22|)))

; find_symbols
(declare-fun |a#2$wclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#2$wclk$8| |a#4$rclk$8|)) (not |memory_model::choice_rf22|)))

; set_to true
(assert (or |memory_model::choice_rf21| |memory_model::choice_rf22|))

; find_symbols
(declare-fun |memory_model::choice_rf23| () Bool)
; set_to true
(assert (or (= |a#5| |a#1|) (not |memory_model::choice_rf23|)))

; find_symbols
(declare-fun |a#5$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#1$wclk$8| |a#5$rclk$8|)) (not |memory_model::choice_rf23|)))

; find_symbols
(declare-fun |memory_model::choice_rf24| () Bool)
; set_to true
(assert (or (= |a#5| |a#2|) (not |memory_model::choice_rf24|)))

; set_to true
(assert (or (not (bvuge |a#2$wclk$8| |a#5$rclk$8|)) (not |memory_model::choice_rf24|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#6|) |memory_model::choice_rf23| |memory_model::choice_rf24|))

; find_symbols
(declare-fun |memory_model::choice_rf25| () Bool)
; set_to true
(assert (or (= |a#7| |a#1|) (not |memory_model::choice_rf25|)))

; find_symbols
(declare-fun |a#7$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#1$wclk$8| |a#7$rclk$8|)) (not |memory_model::choice_rf25|)))

; find_symbols
(declare-fun |memory_model::choice_rf26| () Bool)
; set_to true
(assert (or (= |a#7| |a#2|) (not |memory_model::choice_rf26|)))

; set_to true
(assert (or (not (bvuge |a#2$wclk$8| |a#7$rclk$8|)) (not |memory_model::choice_rf26|)))

; find_symbols
(declare-fun |memory_model::choice_rf27| () Bool)
; set_to true
(assert (or (and (= |a#7| |a#6|) |goto_symex::&92;guard#6|) (not |memory_model::choice_rf27|)))

; set_to true
(assert (or (not (bvuge |a#6$wclk$8| |a#7$rclk$8|)) (not |memory_model::choice_rf27|)))

; set_to true
(assert (or |memory_model::choice_rf25| |memory_model::choice_rf26| |memory_model::choice_rf27|))

; find_symbols
(declare-fun |memory_model::choice_rf28| () Bool)
; set_to true
(assert (or (= |a#8| |a#1|) (not |memory_model::choice_rf28|)))

; find_symbols
(declare-fun |a#8$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |a#1$wclk$8| |a#8$rclk$8|)) (not |memory_model::choice_rf28|)))

; find_symbols
(declare-fun |memory_model::choice_rf29| () Bool)
; set_to true
(assert (or (= |a#8| |a#2|) (not |memory_model::choice_rf29|)))

; set_to true
(assert (or (not (bvuge |a#2$wclk$8| |a#8$rclk$8|)) (not |memory_model::choice_rf29|)))

; find_symbols
(declare-fun |memory_model::choice_rf30| () Bool)
; set_to true
(assert (or (and (= |a#8| |a#6|) |goto_symex::&92;guard#6|) (not |memory_model::choice_rf30|)))

; set_to true
(assert (or (not (bvuge |a#6$wclk$8| |a#8$rclk$8|)) (not |memory_model::choice_rf30|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#7|) |memory_model::choice_rf28| |memory_model::choice_rf29| |memory_model::choice_rf30|))

; find_symbols
(declare-fun |memory_model::choice_rf31| () Bool)
; set_to true
(assert (or (= |b#3| |b#1|) (not |memory_model::choice_rf31|)))

; find_symbols
(declare-fun |b#1$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |b#3$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#1$wclk$8| |b#3$rclk$8|)) (not |memory_model::choice_rf31|)))

; find_symbols
(declare-fun |memory_model::choice_rf32| () Bool)
; set_to true
(assert (or (= |b#3| |b#2|) (not |memory_model::choice_rf32|)))

; find_symbols
(declare-fun |b#2$wclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#2$wclk$8| |b#3$rclk$8|)) (not |memory_model::choice_rf32|)))

; find_symbols
(declare-fun |memory_model::choice_rf33| () Bool)
; set_to true
(assert (or (and (= |b#3| |b#7|) |goto_symex::&92;guard#7|) (not |memory_model::choice_rf33|)))

; find_symbols
(declare-fun |b#7$wclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#7$wclk$8| |b#3$rclk$8|)) (not |memory_model::choice_rf33|)))

; set_to true
(assert (or |memory_model::choice_rf31| |memory_model::choice_rf32| |memory_model::choice_rf33|))

; find_symbols
(declare-fun |memory_model::choice_rf34| () Bool)
; set_to true
(assert (or (= |b#4| |b#1|) (not |memory_model::choice_rf34|)))

; find_symbols
(declare-fun |b#4$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#1$wclk$8| |b#4$rclk$8|)) (not |memory_model::choice_rf34|)))

; find_symbols
(declare-fun |memory_model::choice_rf35| () Bool)
; set_to true
(assert (or (= |b#4| |b#2|) (not |memory_model::choice_rf35|)))

; set_to true
(assert (or (not (bvuge |b#2$wclk$8| |b#4$rclk$8|)) (not |memory_model::choice_rf35|)))

; find_symbols
(declare-fun |memory_model::choice_rf36| () Bool)
; set_to true
(assert (or (and (= |b#4| |b#7|) |goto_symex::&92;guard#7|) (not |memory_model::choice_rf36|)))

; set_to true
(assert (or (not (bvuge |b#7$wclk$8| |b#4$rclk$8|)) (not |memory_model::choice_rf36|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#6|) |memory_model::choice_rf34| |memory_model::choice_rf35| |memory_model::choice_rf36|))

; find_symbols
(declare-fun |memory_model::choice_rf37| () Bool)
; set_to true
(assert (or (= |b#5| |b#1|) (not |memory_model::choice_rf37|)))

; find_symbols
(declare-fun |b#5$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#1$wclk$8| |b#5$rclk$8|)) (not |memory_model::choice_rf37|)))

; find_symbols
(declare-fun |memory_model::choice_rf38| () Bool)
; set_to true
(assert (or (= |b#5| |b#2|) (not |memory_model::choice_rf38|)))

; set_to true
(assert (or (not (bvuge |b#2$wclk$8| |b#5$rclk$8|)) (not |memory_model::choice_rf38|)))

; set_to true
(assert (or |memory_model::choice_rf37| |memory_model::choice_rf38|))

; find_symbols
(declare-fun |memory_model::choice_rf39| () Bool)
; set_to true
(assert (or (= |b#6| |b#1|) (not |memory_model::choice_rf39|)))

; find_symbols
(declare-fun |b#6$rclk$8| () (_ BitVec 6))
; set_to true
(assert (or (not (bvuge |b#1$wclk$8| |b#6$rclk$8|)) (not |memory_model::choice_rf39|)))

; find_symbols
(declare-fun |memory_model::choice_rf40| () Bool)
; set_to true
(assert (or (= |b#6| |b#2|) (not |memory_model::choice_rf40|)))

; set_to true
(assert (or (not (bvuge |b#2$wclk$8| |b#6$rclk$8|)) (not |memory_model::choice_rf40|)))

; set_to true
(assert (or (not |goto_symex::&92;guard#7|) |memory_model::choice_rf39| |memory_model::choice_rf40|))

; find_symbols
(declare-fun |start::1::t1!0@1#3| () (_ BitVec 64))
; find_symbols
(declare-fun |memory_model::choice_rf41| () Bool)
; set_to true
(assert (or (= |start::1::t1!0@1#3| |start::1::t1!0@1#1|) (not |memory_model::choice_rf41|)))

; find_symbols
(declare-fun |memory_model::choice_rf42| () Bool)
; set_to true
(assert (or (= |start::1::t1!0@1#3| |start::1::t1!0@1#2|) (not |memory_model::choice_rf42|)))

; set_to true
(assert (or |memory_model::choice_rf41| |memory_model::choice_rf42|))

; find_symbols
(declare-fun |memory_model::choice_rf43| () Bool)
; set_to true
(assert (or (= |start::1::t1!0@1#4| |start::1::t1!0@1#1|) (not |memory_model::choice_rf43|)))

; find_symbols
(declare-fun |memory_model::choice_rf44| () Bool)
; set_to true
(assert (or (= |start::1::t1!0@1#4| |start::1::t1!0@1#2|) (not |memory_model::choice_rf44|)))

; set_to true
(assert (or |memory_model::choice_rf43| |memory_model::choice_rf44|))

; find_symbols
(declare-fun |start::1::t2!0@1#3| () (_ BitVec 64))
; find_symbols
(declare-fun |memory_model::choice_rf45| () Bool)
; set_to true
(assert (or (= |start::1::t2!0@1#3| |start::1::t2!0@1#1|) (not |memory_model::choice_rf45|)))

; find_symbols
(declare-fun |memory_model::choice_rf46| () Bool)
; set_to true
(assert (or (= |start::1::t2!0@1#3| |start::1::t2!0@1#2|) (not |memory_model::choice_rf46|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) |memory_model::choice_rf45| |memory_model::choice_rf46|))

; find_symbols
(declare-fun |memory_model::choice_rf47| () Bool)
; set_to true
(assert (or (= |start::1::t2!0@1#4| |start::1::t2!0@1#1|) (not |memory_model::choice_rf47|)))

; find_symbols
(declare-fun |memory_model::choice_rf48| () Bool)
; set_to true
(assert (or (= |start::1::t2!0@1#4| |start::1::t2!0@1#2|) (not |memory_model::choice_rf48|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) |memory_model::choice_rf47| |memory_model::choice_rf48|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext49| () Bool)
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_ws-ext49|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#1$wclk$8|)) |memory_model::choice_ws-ext49|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext50| () Bool)
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_ws-ext50|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#1$wclk$8|)) |memory_model::choice_ws-ext50|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext51| () Bool)
; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_ws-ext51|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#5$wclk$8|)) |memory_model::choice_ws-ext51|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext52| () Bool)
; set_to true
(assert (or (not (bvuge |a#1$wclk$8| |a#6$wclk$8|)) (not |memory_model::choice_ws-ext52|)))

; set_to true
(assert (or (not (bvuge |a#6$wclk$8| |a#1$wclk$8|)) |memory_model::choice_ws-ext52|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext53| () Bool)
; set_to true
(assert (or (not (bvuge |a#2$wclk$8| |a#6$wclk$8|)) (not |memory_model::choice_ws-ext53|)))

; set_to true
(assert (or (not (bvuge |a#6$wclk$8| |a#2$wclk$8|)) |memory_model::choice_ws-ext53|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext54| () Bool)
; set_to true
(assert (or (not (bvuge |b#1$wclk$8| |b#7$wclk$8|)) (not |memory_model::choice_ws-ext54|)))

; set_to true
(assert (or (not (bvuge |b#7$wclk$8| |b#1$wclk$8|)) |memory_model::choice_ws-ext54|))

; find_symbols
(declare-fun |memory_model::choice_ws-ext55| () Bool)
; set_to true
(assert (or (not (bvuge |b#2$wclk$8| |b#7$wclk$8|)) (not |memory_model::choice_ws-ext55|)))

; set_to true
(assert (or (not (bvuge |b#7$wclk$8| |b#2$wclk$8|)) |memory_model::choice_ws-ext55|))

; find_symbols
(declare-fun |t1$17$spwnclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |a#4$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |b#3$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |a#5$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |b#4$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |a#6$wclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |__CPROVER_threads_exited#4$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |__CPROVER_threads_exited#5$wclk$8|)))

; find_symbols
(declare-fun |t1$21$spwnclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |b#5$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |a#7$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |b#6$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |a#8$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |b#7$wclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |__CPROVER_threads_exited#6$rclk$8|)))

; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |__CPROVER_threads_exited#7$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_dead_object#1$wclk$8| () (_ BitVec 6))
; find_symbols
(declare-fun |__CPROVER_deallocated#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_dead_object#1$wclk$8| |__CPROVER_deallocated#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_malloc_is_new_array#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_deallocated#1$wclk$8| |__CPROVER_malloc_is_new_array#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_malloc_object#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_malloc_is_new_array#1$wclk$8| |__CPROVER_malloc_object#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_malloc_size#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_malloc_object#1$wclk$8| |__CPROVER_malloc_size#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_memory_leak#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_malloc_size#1$wclk$8| |__CPROVER_memory_leak#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_memory_leak#1$wclk$8| |__CPROVER_next_thread_id#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_pipe_count#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_next_thread_id#1$wclk$8| |__CPROVER_pipe_count#1$wclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_pipe_count#1$wclk$8| |__CPROVER_threads_exited#1$wclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_threads_exited#1$wclk$8| |a#1$wclk$8|)))

; set_to false
(assert (not (bvuge |a#1$wclk$8| |b#1$wclk$8|)))

; set_to false
(assert (not (bvuge |b#1$wclk$8| |a#2$wclk$8|)))

; set_to false
(assert (not (bvuge |a#2$wclk$8| |b#2$wclk$8|)))

; find_symbols
(declare-fun |start::1::t1!0@1#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |b#2$wclk$8| |start::1::t1!0@1#1$wclk$8|)))

; find_symbols
(declare-fun |start::1::t2!0@1#1$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t1!0@1#1$wclk$8| |start::1::t2!0@1#1$wclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#2$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t2!0@1#1$wclk$8| |__CPROVER_next_thread_id#2$wclk$8|)))

; find_symbols
(declare-fun |start::1::t1!0@1#2$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_next_thread_id#2$wclk$8| |start::1::t1!0@1#2$wclk$8|)))

; set_to false
(assert (not (bvuge |start::1::t1!0@1#2$wclk$8| |t1$17$spwnclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#3$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |t1$17$spwnclk$8| |__CPROVER_next_thread_id#3$rclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#5$wclk$8| () (_ BitVec 6))
; set_to true
(assert (= |__CPROVER_next_thread_id#3$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|))

; find_symbols
(declare-fun |start::1::t2!0@1#2$wclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_next_thread_id#5$wclk$8| |start::1::t2!0@1#2$wclk$8|)))

; set_to false
(assert (not (bvuge |start::1::t2!0@1#2$wclk$8| |t1$21$spwnclk$8|)))

; find_symbols
(declare-fun |start::1::t1!0@1#3$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |t1$21$spwnclk$8| |start::1::t1!0@1#3$rclk$8|)))

; find_symbols
(declare-fun |start::1::t1!0@1#4$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t1!0@1#3$rclk$8| |start::1::t1!0@1#4$rclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#6$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t1!0@1#4$rclk$8| |__CPROVER_next_thread_id#6$rclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_next_thread_id#6$rclk$8| |__CPROVER_threads_exited#2$rclk$8|)))

; find_symbols
(declare-fun |start::1::t2!0@1#3$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |start::1::t2!0@1#3$rclk$8|)))

; find_symbols
(declare-fun |start::1::t2!0@1#4$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t2!0@1#3$rclk$8| |start::1::t2!0@1#4$rclk$8|)))

; find_symbols
(declare-fun |__CPROVER_next_thread_id#7$rclk$8| () (_ BitVec 6))
; set_to false
(assert (not (bvuge |start::1::t2!0@1#4$rclk$8| |__CPROVER_next_thread_id#7$rclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_next_thread_id#7$rclk$8| |__CPROVER_threads_exited#3$rclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |a#3$rclk$8|)))

; set_to false
(assert (not (bvuge |a#4$rclk$8| |b#3$rclk$8|)))

; set_to false
(assert (not (bvuge |b#3$rclk$8| |a#5$rclk$8|)))

; set_to false
(assert (not (bvuge |a#5$rclk$8| |b#4$rclk$8|)))

; set_to false
(assert (not (bvuge |b#4$rclk$8| |a#6$wclk$8|)))

; set_to false
(assert (not (bvuge |a#6$wclk$8| |__CPROVER_threads_exited#4$rclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_threads_exited#4$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)))

; set_to false
(assert (not (bvuge |b#5$rclk$8| |a#7$rclk$8|)))

; set_to false
(assert (not (bvuge |a#7$rclk$8| |b#6$rclk$8|)))

; set_to false
(assert (not (bvuge |b#6$rclk$8| |a#8$rclk$8|)))

; set_to false
(assert (not (bvuge |a#8$rclk$8| |b#7$wclk$8|)))

; set_to false
(assert (not (bvuge |b#7$wclk$8| |__CPROVER_threads_exited#6$rclk$8|)))

; set_to false
(assert (not (bvuge |__CPROVER_threads_exited#6$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (not (bvuge |__CPROVER_threads_exited#4$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf6|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf1|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf0|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (not (bvuge |__CPROVER_threads_exited#6$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf9|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (not (bvuge |__CPROVER_threads_exited#6$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf8|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf4|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf3|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (not (bvuge |__CPROVER_threads_exited#4$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf6|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (not (bvuge |__CPROVER_threads_exited#4$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf7|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf0|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf2|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (not (bvuge |__CPROVER_threads_exited#6$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf8|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#1$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf3|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#1$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#1$wclk$8|)) (not |memory_model::choice_rf5|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (not (bvuge |__CPROVER_threads_exited#4$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf7|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf1|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (not (bvuge |__CPROVER_threads_exited#2$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf2|) |goto_symex::&92;guard#1| |goto_symex::&92;guard#2|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (not (bvuge |__CPROVER_threads_exited#6$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf9|)))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#5$wclk$8| |__CPROVER_threads_exited#7$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#7$wclk$8|)) (not |memory_model::choice_rf4|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (bvuge |__CPROVER_threads_exited#7$wclk$8| |__CPROVER_threads_exited#5$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_threads_exited#3$rclk$8| |__CPROVER_threads_exited#5$wclk$8|)) (not |memory_model::choice_rf5|) |goto_symex::&92;guard#3| |goto_symex::&92;guard#4|))

; set_to true
(assert (or (not (bvuge |__CPROVER_next_thread_id#6$rclk$8| |__CPROVER_next_thread_id#2$wclk$8|)) (not |memory_model::choice_rf12|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_next_thread_id#7$rclk$8| |__CPROVER_next_thread_id#2$wclk$8|)) (not |memory_model::choice_rf15|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_next_thread_id#3$rclk$8| |__CPROVER_next_thread_id#2$wclk$8|)) (not |memory_model::choice_rf10|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_next_thread_id#6$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|)) (not |memory_model::choice_rf12|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_next_thread_id#7$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|)) (not |memory_model::choice_rf15|)))

; set_to true
(assert (or (= |__CPROVER_next_thread_id#3$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|) (not |memory_model::choice_rf10|)))

; set_to true
(assert (or (not (bvuge |__CPROVER_next_thread_id#6$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|)) (not |memory_model::choice_rf13|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |__CPROVER_next_thread_id#7$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|)) (not |memory_model::choice_rf16|)))

; set_to true
(assert (or (= |__CPROVER_next_thread_id#3$rclk$8| |__CPROVER_next_thread_id#5$wclk$8|) (not |memory_model::choice_rf11|)))

; set_to true
(assert (or (not (bvuge |a#4$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf21|)))

; set_to true
(assert (or (not (bvuge |a#8$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf28|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) (not (bvuge |a#3$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf18|)))

; set_to true
(assert (or (not (bvuge |a#5$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf23|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (not (bvuge |a#7$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf25|)))

; set_to true
(assert (or (bvuge |a#1$wclk$8| |a#6$wclk$8|) (not (bvuge |a#4$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf21|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#1$wclk$8|) (not (bvuge |a#8$rclk$8| |a#1$wclk$8|)) (not |memory_model::choice_rf30|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |a#1$wclk$8| |a#6$wclk$8|) (not (bvuge |a#8$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf28|) (not |goto_symex::&92;guard#6|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#1$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) (not (bvuge |a#3$rclk$8| |a#1$wclk$8|)) (not |memory_model::choice_rf20|)))

; set_to true
(assert (or (bvuge |a#1$wclk$8| |a#6$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) (not (bvuge |a#3$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf18|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#1$wclk$8| |a#6$wclk$8|) (not (bvuge |a#5$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf23|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#1$wclk$8|) (not (bvuge |a#7$rclk$8| |a#1$wclk$8|)) (not |memory_model::choice_rf27|)))

; set_to true
(assert (or (bvuge |a#1$wclk$8| |a#6$wclk$8|) (not (bvuge |a#7$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf25|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#2$wclk$8| |a#6$wclk$8|) (not (bvuge |a#4$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf22|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#2$wclk$8|) (not (bvuge |a#8$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf30|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |a#2$wclk$8| |a#6$wclk$8|) (not (bvuge |a#8$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf29|) (not |goto_symex::&92;guard#6|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#2$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) (not (bvuge |a#3$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf20|)))

; set_to true
(assert (or (bvuge |a#2$wclk$8| |a#6$wclk$8|) (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (and (or |goto_symex::&92;guard#3| (and (or (not (select |__CPROVER_threads_exited#3| |pthread_join::thread!0@2#1|)) |goto_symex::&92;guard#4|) (not |goto_symex::&92;guard#4|))) (not |goto_symex::&92;guard#3|)) (not (bvuge |a#3$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf19|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#2$wclk$8| |a#6$wclk$8|) (not (bvuge |a#5$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf24|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |a#6$wclk$8| |a#2$wclk$8|) (not (bvuge |a#7$rclk$8| |a#2$wclk$8|)) (not |memory_model::choice_rf27|)))

; set_to true
(assert (or (bvuge |a#2$wclk$8| |a#6$wclk$8|) (not (bvuge |a#7$rclk$8| |a#6$wclk$8|)) (not |memory_model::choice_rf26|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (not (bvuge |b#3$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf31|)))

; set_to true
(assert (or (not (bvuge |b#5$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf37|)))

; set_to true
(assert (or (not (bvuge |b#6$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf39|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (not (bvuge |b#4$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf34|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |b#7$wclk$8| |b#1$wclk$8|) (not (bvuge |b#3$rclk$8| |b#1$wclk$8|)) (not |memory_model::choice_rf33|)))

; set_to true
(assert (or (bvuge |b#1$wclk$8| |b#7$wclk$8|) (not (bvuge |b#3$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf31|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#1$wclk$8| |b#7$wclk$8|) (not (bvuge |b#5$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf37|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#1$wclk$8| |b#7$wclk$8|) (not (bvuge |b#6$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf39|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#7$wclk$8| |b#1$wclk$8|) (not (bvuge |b#4$rclk$8| |b#1$wclk$8|)) (not |memory_model::choice_rf36|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |b#1$wclk$8| |b#7$wclk$8|) (not (bvuge |b#4$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf34|) (not |goto_symex::&92;guard#6|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#7$wclk$8| |b#2$wclk$8|) (not (bvuge |b#3$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf33|)))

; set_to true
(assert (or (bvuge |b#2$wclk$8| |b#7$wclk$8|) (not (bvuge |b#3$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf32|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#2$wclk$8| |b#7$wclk$8|) (not (bvuge |b#5$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf38|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#2$wclk$8| |b#7$wclk$8|) (not (bvuge |b#6$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf40|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (bvuge |b#7$wclk$8| |b#2$wclk$8|) (not (bvuge |b#4$rclk$8| |b#2$wclk$8|)) (not |memory_model::choice_rf36|) (not |goto_symex::&92;guard#6|)))

; set_to true
(assert (or (bvuge |b#2$wclk$8| |b#7$wclk$8|) (not (bvuge |b#4$rclk$8| |b#7$wclk$8|)) (not |memory_model::choice_rf35|) (not |goto_symex::&92;guard#6|) (not |goto_symex::&92;guard#7|)))

; set_to true
(assert (or (not (bvuge |start::1::t1!0@1#4$rclk$8| |start::1::t1!0@1#2$wclk$8|)) (not |memory_model::choice_rf43|)))

; set_to true
(assert (or (not (bvuge |start::1::t1!0@1#3$rclk$8| |start::1::t1!0@1#2$wclk$8|)) (not |memory_model::choice_rf41|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |start::1::t2!0@1#3$rclk$8| |start::1::t2!0@1#2$wclk$8|)) (not |memory_model::choice_rf45|)))

; set_to true
(assert (or (and (or |goto_symex::&92;guard#1| (and (or (not (select |__CPROVER_threads_exited#2| |pthread_join::thread!0@1#1|)) |goto_symex::&92;guard#2|) (not |goto_symex::&92;guard#2|))) (not |goto_symex::&92;guard#1|)) (not (bvuge |start::1::t2!0@1#4$rclk$8| |start::1::t2!0@1#2$wclk$8|)) (not |memory_model::choice_rf47|)))

; set to true fixed
(assert |memory_model::choice_rf1|)
; set to true fixed
(assert |memory_model::choice_rf2|)
; set to true fixed
(assert |memory_model::choice_rf4|)
; set to true fixed
(assert |memory_model::choice_rf5|)
(check-sat)

(get-value (|B0|))
(get-value (|B1|))
(get-value (|B10|))
(get-value (|B11|))
(get-value (|B12|))
(get-value (|B13|))
(get-value (|B14|))
(get-value (|B15|))
(get-value (|B16|))
(get-value (|B17|))
(get-value (|B18|))
(get-value (|B19|))
(get-value (|B2|))
(get-value (|B20|))
(get-value (|B21|))
(get-value (|B22|))
(get-value (|B23|))
(get-value (|B24|))
(get-value (|B25|))
(get-value (|B26|))
(get-value (|B27|))
(get-value (|B28|))
(get-value (|B29|))
(get-value (|B3|))
(get-value (|B30|))
(get-value (|B31|))
(get-value (|B32|))
(get-value (|B33|))
(get-value (|B34|))
(get-value (|B35|))
(get-value (|B36|))
(get-value (|B37|))
(get-value (|B38|))
(get-value (|B39|))
(get-value (|B4|))
(get-value (|B40|))
(get-value (|B41|))
(get-value (|B42|))
(get-value (|B43|))
(get-value (|B44|))
(get-value (|B45|))
(get-value (|B46|))
(get-value (|B47|))
(get-value (|B48|))
(get-value (|B49|))
(get-value (|B5|))
(get-value (|B50|))
(get-value (|B51|))
(get-value (|B52|))
(get-value (|B53|))
(get-value (|B54|))
(get-value (|B55|))
(get-value (|B56|))
(get-value (|B57|))
(get-value (|B58|))
(get-value (|B59|))
(get-value (|B6|))
(get-value (|B60|))
(get-value (|B61|))
(get-value (|B62|))
(get-value (|B63|))
(get-value (|B64|))
(get-value (|B65|))
(get-value (|B66|))
(get-value (|B67|))
(get-value (|B68|))
(get-value (|B7|))
(get-value (|B8|))
(get-value (|B9|))
(get-value (|__CPROVER_dead_object#1|))
(get-value (|__CPROVER_dead_object#1$wclk$8|))
(get-value (|__CPROVER_deallocated#1|))
(get-value (|__CPROVER_deallocated#1$wclk$8|))
(get-value (|__CPROVER_malloc_is_new_array#1|))
(get-value (|__CPROVER_malloc_is_new_array#1$wclk$8|))
(get-value (|__CPROVER_malloc_object#1|))
(get-value (|__CPROVER_malloc_object#1$wclk$8|))
(get-value (|__CPROVER_malloc_size#1|))
(get-value (|__CPROVER_malloc_size#1$wclk$8|))
(get-value (|__CPROVER_memory_leak#1|))
(get-value (|__CPROVER_memory_leak#1$wclk$8|))
(get-value (|__CPROVER_next_thread_id#1|))
(get-value (|__CPROVER_next_thread_id#1$wclk$8|))
(get-value (|__CPROVER_next_thread_id#2|))
(get-value (|__CPROVER_next_thread_id#2$wclk$8|))
(get-value (|__CPROVER_next_thread_id#3|))
(get-value (|__CPROVER_next_thread_id#3$rclk$8|))
(get-value (|__CPROVER_next_thread_id#4|))
(get-value (|__CPROVER_next_thread_id#5|))
(get-value (|__CPROVER_next_thread_id#5$wclk$8|))
(get-value (|__CPROVER_next_thread_id#6|))
(get-value (|__CPROVER_next_thread_id#6$rclk$8|))
(get-value (|__CPROVER_next_thread_id#7|))
(get-value (|__CPROVER_next_thread_id#7$rclk$8|))
(get-value (|__CPROVER_pipe_count#1|))
(get-value (|__CPROVER_pipe_count#1$wclk$8|))
(get-value (|__CPROVER_rounding_mode!0#1|))
(get-value (|__CPROVER_rounding_mode!1#1|))
(get-value (|__CPROVER_rounding_mode!2#1|))
(get-value (|__CPROVER_thread_id!0#1|))
(get-value (|__CPROVER_thread_id!1#1|))
(get-value (|__CPROVER_thread_id!1#2|))
(get-value (|__CPROVER_thread_id!2#1|))
(get-value (|__CPROVER_thread_id!2#2|))
(get-value (|__CPROVER_threads_exited#1|))
(get-value (|__CPROVER_threads_exited#1$wclk$8|))
(get-value (|__CPROVER_threads_exited#2|))
(get-value (|__CPROVER_threads_exited#2$rclk$8|))
(get-value (|__CPROVER_threads_exited#3|))
(get-value (|__CPROVER_threads_exited#3$rclk$8|))
(get-value (|__CPROVER_threads_exited#4|))
(get-value (|__CPROVER_threads_exited#4$rclk$8|))
(get-value (|__CPROVER_threads_exited#5|))
(get-value (|__CPROVER_threads_exited#5$wclk$8|))
(get-value (|__CPROVER_threads_exited#6|))
(get-value (|__CPROVER_threads_exited#6$rclk$8|))
(get-value (|__CPROVER_threads_exited#7|))
(get-value (|__CPROVER_threads_exited#7$wclk$8|))
(get-value (|__VERIFIER_assert::cond!0@1#1|))
(get-value (|a#1|))
(get-value (|a#1$wclk$8|))
(get-value (|a#2|))
(get-value (|a#2$wclk$8|))
(get-value (|a#3|))
(get-value (|a#3$rclk$8|))
(get-value (|a#4|))
(get-value (|a#4$rclk$8|))
(get-value (|a#5|))
(get-value (|a#5$rclk$8|))
(get-value (|a#6|))
(get-value (|a#6$wclk$8|))
(get-value (|a#7|))
(get-value (|a#7$rclk$8|))
(get-value (|a#8|))
(get-value (|a#8$rclk$8|))
(get-value (|b#1|))
(get-value (|b#1$wclk$8|))
(get-value (|b#2|))
(get-value (|b#2$wclk$8|))
(get-value (|b#3|))
(get-value (|b#3$rclk$8|))
(get-value (|b#4|))
(get-value (|b#4$rclk$8|))
(get-value (|b#5|))
(get-value (|b#5$rclk$8|))
(get-value (|b#6|))
(get-value (|b#6$rclk$8|))
(get-value (|b#7|))
(get-value (|b#7$wclk$8|))
(get-value (|check_gcd::a_in!0@1#1|))
(get-value (|check_gcd::b_in!0@1#1|))
(get-value (|check_gcd::gcd!0@1#1|))
(get-value (|dec_a#return_value!1#1|))
(get-value (|dec_a#return_value!1#2|))
(get-value (|dec_a#return_value!2#1|))
(get-value (|dec_a::arg!1@1#1|))
(get-value (|dec_b#return_value!1#1|))
(get-value (|dec_b#return_value!2#1|))
(get-value (|dec_b#return_value!2#2|))
(get-value (|dec_b::arg!2@1#1|))
(get-value (|goto_symex::&92;guard#1|))
(get-value (|goto_symex::&92;guard#2|))
(get-value (|goto_symex::&92;guard#3|))
(get-value (|goto_symex::&92;guard#4|))
(get-value (|goto_symex::&92;guard#5|))
(get-value (|goto_symex::&92;guard#6|))
(get-value (|goto_symex::&92;guard#7|))
(get-value (|main#return_value!0#1|))
(get-value (|main#return_value!1#1|))
(get-value (|main#return_value!2#1|))
(get-value (|main::$tmp::return_value_start!0@1#1|))
(get-value (|main::$tmp::return_value_start!0@1#2|))
(get-value (|main::1::a_in!0@1#1|))
(get-value (|main::1::a_in!0@1#2|))
(get-value (|main::1::b_in!0@1#1|))
(get-value (|main::1::b_in!0@1#2|))
(get-value (|memory_model::choice_rf0|))
(get-value (|memory_model::choice_rf1|))
(get-value (|memory_model::choice_rf10|))
(get-value (|memory_model::choice_rf11|))
(get-value (|memory_model::choice_rf12|))
(get-value (|memory_model::choice_rf13|))
(get-value (|memory_model::choice_rf14|))
(get-value (|memory_model::choice_rf15|))
(get-value (|memory_model::choice_rf16|))
(get-value (|memory_model::choice_rf17|))
(get-value (|memory_model::choice_rf18|))
(get-value (|memory_model::choice_rf19|))
(get-value (|memory_model::choice_rf2|))
(get-value (|memory_model::choice_rf20|))
(get-value (|memory_model::choice_rf21|))
(get-value (|memory_model::choice_rf22|))
(get-value (|memory_model::choice_rf23|))
(get-value (|memory_model::choice_rf24|))
(get-value (|memory_model::choice_rf25|))
(get-value (|memory_model::choice_rf26|))
(get-value (|memory_model::choice_rf27|))
(get-value (|memory_model::choice_rf28|))
(get-value (|memory_model::choice_rf29|))
(get-value (|memory_model::choice_rf3|))
(get-value (|memory_model::choice_rf30|))
(get-value (|memory_model::choice_rf31|))
(get-value (|memory_model::choice_rf32|))
(get-value (|memory_model::choice_rf33|))
(get-value (|memory_model::choice_rf34|))
(get-value (|memory_model::choice_rf35|))
(get-value (|memory_model::choice_rf36|))
(get-value (|memory_model::choice_rf37|))
(get-value (|memory_model::choice_rf38|))
(get-value (|memory_model::choice_rf39|))
(get-value (|memory_model::choice_rf4|))
(get-value (|memory_model::choice_rf40|))
(get-value (|memory_model::choice_rf41|))
(get-value (|memory_model::choice_rf42|))
(get-value (|memory_model::choice_rf43|))
(get-value (|memory_model::choice_rf44|))
(get-value (|memory_model::choice_rf45|))
(get-value (|memory_model::choice_rf46|))
(get-value (|memory_model::choice_rf47|))
(get-value (|memory_model::choice_rf48|))
(get-value (|memory_model::choice_rf5|))
(get-value (|memory_model::choice_rf6|))
(get-value (|memory_model::choice_rf7|))
(get-value (|memory_model::choice_rf8|))
(get-value (|memory_model::choice_rf9|))
(get-value (|memory_model::choice_ws-ext49|))
(get-value (|memory_model::choice_ws-ext50|))
(get-value (|memory_model::choice_ws-ext51|))
(get-value (|memory_model::choice_ws-ext52|))
(get-value (|memory_model::choice_ws-ext53|))
(get-value (|memory_model::choice_ws-ext54|))
(get-value (|memory_model::choice_ws-ext55|))
(get-value (|pthread_create#return_value!0#1|))
(get-value (|pthread_create#return_value!0#2|))
(get-value (|pthread_create#return_value!1#1|))
(get-value (|pthread_create#return_value!2#1|))
(get-value (|pthread_create::1::this_thread_id!0@1#1|))
(get-value (|pthread_create::1::this_thread_id!0@1#2|))
(get-value (|pthread_create::1::this_thread_id!0@2#1|))
(get-value (|pthread_create::1::this_thread_id!0@2#2|))
(get-value (|pthread_create::1::this_thread_id!1@0#0|))
(get-value (|pthread_create::1::this_thread_id!2@0#0|))
(get-value (|pthread_create::arg!0@1#1|))
(get-value (|pthread_create::arg!0@2#1|))
(get-value (|pthread_create::arg!1@0#1|))
(get-value (|pthread_create::arg!2@0#1|))
(get-value (|pthread_create::attr!0@1#1|))
(get-value (|pthread_create::attr!0@2#1|))
(get-value (|pthread_create::attr!1@0#1|))
(get-value (|pthread_create::attr!2@0#1|))
(get-value (|pthread_create::start_routine!0@1#1|))
(get-value (|pthread_create::start_routine!0@2#1|))
(get-value (|pthread_create::start_routine!1@0#1|))
(get-value (|pthread_create::start_routine!2@0#1|))
(get-value (|pthread_create::thread!0@1#1|))
(get-value (|pthread_create::thread!0@2#1|))
(get-value (|pthread_create::thread!1@0#1|))
(get-value (|pthread_create::thread!2@0#1|))
(get-value (|pthread_join#return_value!0#0|))
(get-value (|pthread_join#return_value!0#1|))
(get-value (|pthread_join#return_value!0#10|))
(get-value (|pthread_join#return_value!0#11|))
(get-value (|pthread_join#return_value!0#12|))
(get-value (|pthread_join#return_value!0#13|))
(get-value (|pthread_join#return_value!0#14|))
(get-value (|pthread_join#return_value!0#2|))
(get-value (|pthread_join#return_value!0#3|))
(get-value (|pthread_join#return_value!0#4|))
(get-value (|pthread_join#return_value!0#5|))
(get-value (|pthread_join#return_value!0#6|))
(get-value (|pthread_join#return_value!0#7|))
(get-value (|pthread_join#return_value!0#8|))
(get-value (|pthread_join#return_value!0#9|))
(get-value (|pthread_join#return_value!1#1|))
(get-value (|pthread_join#return_value!2#1|))
(get-value (|pthread_join::thread!0@1#1|))
(get-value (|pthread_join::thread!0@2#1|))
(get-value (|pthread_join::value_ptr!0@1#1|))
(get-value (|pthread_join::value_ptr!0@2#1|))
(get-value (|return'!0#1|))
(get-value (|start#return_value!0#1|))
(get-value (|start#return_value!1#1|))
(get-value (|start#return_value!2#1|))
(get-value (|start::1::t1!0@1|))
(get-value (|start::1::t1!0@1#1|))
(get-value (|start::1::t1!0@1#1$wclk$8|))
(get-value (|start::1::t1!0@1#2|))
(get-value (|start::1::t1!0@1#2$wclk$8|))
(get-value (|start::1::t1!0@1#3|))
(get-value (|start::1::t1!0@1#3$rclk$8|))
(get-value (|start::1::t1!0@1#4|))
(get-value (|start::1::t1!0@1#4$rclk$8|))
(get-value (|start::1::t2!0@1|))
(get-value (|start::1::t2!0@1#1|))
(get-value (|start::1::t2!0@1#1$wclk$8|))
(get-value (|start::1::t2!0@1#2|))
(get-value (|start::1::t2!0@1#2$wclk$8|))
(get-value (|start::1::t2!0@1#3|))
(get-value (|start::1::t2!0@1#3$rclk$8|))
(get-value (|start::1::t2!0@1#4|))
(get-value (|start::1::t2!0@1#4$rclk$8|))
(get-value (|start::a_in!0@1#1|))
(get-value (|start::b_in!0@1#1|))
(get-value (|t1$17$spwnclk$8|))
(get-value (|t1$21$spwnclk$8|))

(exit)
; end of SMT2 file
